[package]
name = "mc64"
version = "0.1.1"
description = "Sparse matrix scalings"
license = "BSD-3-Clause"
repository = "https://github.com/rwl/mc64"
edition = "2021"

[dependencies]
num-traits = "0.2"
#rand = "0.9.0"

#[dev-dependencies]
#spral = { path = "../spral", features = ["static_libraries"] }
#spral = { path = "../spral", features = ["shared_libraries"] }
